---
title: "Contact the Sandbox"
listing:
  fields: [image, title, description]
  contents: ../cards/*.qmd
  type: grid
  image-height: 300px
  grid-columns: 5
format:
  html:
    page-layout: full
---

The Health Data Science Sandbox is coordinated by the [Center for Health Data Science](https://heads.ku.dk/)
at the University of Copenhagen (KU). Sandbox data scientists are also placed in collaborating groups at
the Technical University of Denmark (DTU), University of Southern Denmark (SDU), Aarhus University (AU),
and Aalborg University (AAU).

To get in touch with the Sandbox or be connected with Sandbox staff at your university,
please [email us](mailto:nhds_sandbox@sund.ku.dk). To obtain module material for use in your
own compute environment, see our GitHub organization page
at [hds-sandbox](https://github.com/hds-sandbox/).

| Member                        | Role                                | Institution                        | PI                                 |
|-------------------------------|-------------------------------------|------------------------------------|------------------------------------|
| Jennifer Bartell              | Project Manager, Data Scientist | Center for Health Data Science, KU |Anders Krogh                        |
| Alba Refoyo Martinez          | Data Scientist                      | Center for Health Data Science, KU |Anders Krogh                        |
| Jakob Skelmose                | Data Scientist                      | Department of Clinical Medicine, AAU|Martin Boegsted                    |
| Samuele Soraggi               | Data Scientist                      | Bioinformatics Research Centre, AU |Mikkel Schierup                     |
| Jesper Roy Christiansen       | Data Scientist                      | Computerome, DTU                   |Peter Loengreen                     |
| Jacob Fredegaard Hansen       | Data Scientist                      | Department of Biochemistry and Molecular Biology, SDU|Ole Noerregaard Jensen|

<style>
table {
  font-size: 16px; /* Set the desired font size here */
}
</style>



We appreciate the contributions of previous team members José Alejandro Romero Herrera (KU), Conor O'Hare (KU), Sander Boisen Valentin (AAU) and Peter Husen (SDU).


Find all the team members and their contacts below. Click on their names for more information about each member of the team: