#!/bin/bash

## environment
ENVSM=base

FLAG=0

while getopts c: option
do
    case "${option}"
    in
        c) COURSE=${OPTARG};;
        \?) ## Invalid option
            printf "Error: invalid option.\n\n"
            exit;;
    esac
done


if [ -f "${PYTHON_DEPS}" ]
then

    printf  "\n===================================  "
    printf  "\n Installing dependencies for the Course  \n"
    printf  "===================================  \n\n"

    if [[ "${COURSE}" == "NGS Summer" ]]
    then

	eval "$(conda shell.bash hook)"
	conda create -n scrna-python
	conda install -n scrna-python -c conda-forge scanpy==1.9.1 leidenalg=0.8.10 python-igraph==0.9.10
	python -m ipykernel install --user --name scrna-python --display-name "Python (scRNA)"
	mkdir introduction_to_scrna_analysis
	cd introduction_to_scrna_analysis
	git init
	git remote add origin https://github.com/hds-sandbox/scRNASeq_course.git
	git config core.sparseCheckout true
	echo "Assignments/" >> .git/info/sparse-checkout
	echo "Environments/" >> .git/info/sparse-checkout
	echo "Notebooks/" >> .git/info/sparse-checkout
	echo "Scripts/" >> .git/info/sparse-checkout
	git pull --depth=1 origin main

    else
        echo "No Course"
        echo ""
    fi

fi

#if [ -f "${BATCH_SCRIPT}" ]
#then
#
#    printf  "\n=====================  "
#    printf  "\n Submit batch script  \n"
#    printf  "=====================  \n\n"
#
#    bash "${BATCH_SCRIPT}"
#    exit 0
#
#fi

printf  "\n==================  "
printf  "\n Start JupyterLab  \n"
printf  "==================  \n\n"

bash -c "jupyter lab --NotebookApp.token='' "

