#!/bin/bash

## environment
ENVSM=base

FLAG=0

MATERIAL_FOLDER="None"


while getopts c:m: option
do
    case "${option}"
    in
        c) COURSE=${OPTARG};;
        m) MATERIAL_FOLDER=${OPTARG};;
        \?) ## Invalid option
            printf "Error: invalid option.\n\n"
            exit;;
    esac
done


if [[ "${COURSE}" == "NGS Summer" ]]
then
    if [[ "${MATERIAL_FOLDER}" == "None" ]]
    then

        printf  "\n===================================  "
        printf  "\n Downloading Course Material  \n"
        printf  "===================================  \n\n"

        mkdir introduction_to_scrna_analysis
        cd introduction_to_scrna_analysis
        git init
        git remote add origin https://github.com/hds-sandbox/scRNASeq_course.git
        git config core.sparseCheckout true
        echo "Assignments/" >> .git/info/sparse-checkout
        echo "Environments/" >> .git/info/sparse-checkout
        echo "Notebooks/" >> .git/info/sparse-checkout
        echo "Scripts/" >> .git/info/sparse-checkout
        git pull --depth=1 origin main

    else

        printf  "\n===================================  "
        printf  "\n Copying Chosen Course Material \n"
        printf  "===================================  \n\n"
        cp -a ${COURSE_MATERIAL} .

    fi

else

    echo "No Course"
    echo ""

fi


#if [ -f "${BATCH_SCRIPT}" ]
#then
#
#    printf  "\n=====================  "
#    printf  "\n Submit batch script  \n"
#    printf  "=====================  \n\n"
#
#    bash "${BATCH_SCRIPT}"
#    exit 0
#
#fi

printf  "\n==================  "
printf  "\n Start JupyterLab  \n"
printf  "==================  \n\n"

bash -c "jupyter lab --NotebookApp.token='' "

