---
title: "Second bulk RNA-seq course at the University of Copenhagen"
description: "Second bulk RNA-seq course at the University of Copenhagen"
Organizers: Jennifer Bartell
date: 2023-01-18
Dates: "18 January 2023"
Location: KU 
categories: [workshop, course, KU, nextflow]
---

On 18th of January we taught the second iteration of our bulk RNA-seq course to researchers (from PhD students to professors) at SUND at the University of Copenhagen. We had ~50 workshop participants joining us for three days of lectures and exercises on UCloud. This time, we introduced preprocessing theory (read QC, alignment and quantification) and the use of automated workflows using the [nf-core rnaseq pipeline](https://nf-co.re/rnaseq).

For those that could not enroll for this session, you can find the updated material [here](https://hds-sandbox.github.io/bulk_RNAseq_course/). We have moved the datasets and slides to a [zenodo repository](https://zenodo.org/record/7565997)

We'd like to extend our thanks to our workshop collaborators, data scientists from the SUND DataLab at KU's Center for Health Data Science as well as the genomics platform at the NNF Center for Stem Cell Medicine (reNEW). 